FROM wordpress:php8.1-fpm-alpine

ENV PHPREDIS_VERSION=5.3.7

RUN apk update \
  && apk add git

RUN docker-php-source extract \
  && curl -L -o /tmp/redis.tar.gz https://github.com/endangeredtoast/wordpress-stack/blob/main/docker/phpredis-5.3.7.zip \
#  && curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz \
  && tar xfz /tmp/redis.tar.gz \
  && mv phpredis-$PHPREDIS_VERSION /usr/src/php/ext/redis \
  && docker-php-ext-install redis
